version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"
    mkdocs:
      version: latest

python:
  install:
    - requirements: docs/requirements.txt

mkdocs:
  configuration: docs/mkdocs.yml
